### ISSUE TITLE
Idea: Do not require to configure document type name

### ISSUE THREAD

**Issue by mvar** [ongr-io/RouterBundle#66]
Now we have:

```yml
ongr_router:
    seo_routes:
        product: AppBundle:Product:show
```

What about this:

```yml
ongr_router:
    seo_routes:
        - AppBundle:Product:show
```

When we know controller and action we can get Document class (and later ES type name) from typehintings. 

The only drawback I see here is that we would force to use typehinting of concrete document. In some cases single controller's action could be reused for multiple documents.

Just an idea. Let it sit for few days and we will decide if it's worth something.
