### ISSUE TITLE
If in project another chain router is used ONGR router doesn't work.

### ISSUE THREAD

**Issue by saimaz** [ongr-io/RouterBundle#86]
Some comments from gitter chat.

@funkdoobiest wrote:

Ok, seems like I found something
in ONGR\RouterBundle\DependencyInjection\Compiler\SetRouterPass

```php
<?php

namespace ONGR\RouterBundle\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

class SetRouterPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        //$container->setAlias('router', 'ongr_router.chain_router');
        $container
            ->getDefinition('ongr_router.elasticsearch_route_provider')
            ->addMethodCall(
                'setManager',
                [new Reference($container->getParameter('ongr_router.manager'))]
            );
    }
}
```

I commented first line in function and now it seems to work.
did not finished testing all things, but first look is good.
as I can see, some services in "ez platform" are getting router with "@router" param
and then it will get this alias from ongr which are without the "ez" routers
like here:

```yml

ezpublish.controller.content.download_redirection:
        class: %ezpublish.controller.content.download_redirection.class%
        arguments:
            - @ezpublish.api.service.content
            - @router
            - @ezpublish.route_reference.generator
        parent: ezpublish.controller.base

```

in other classes I can see that "ez" is getting all services tagged "router" and then everything worked fine
but all with `@router` failed

I hope my bad english was not to confusing
wrote this late at night
